import type { Metadata } from "next";
import './globals.css'

import Providers from "./providers";
import { AuthProvider } from "@/contexts/AuthContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
         <body className="font-sans bg-gray-100 text-gray-900">

          <AuthProvider>
              <Providers >
                 {children}
            </Providers>
          </AuthProvider>
       
      </body>
    </html>
  );
}
